[package]
name = "open-oak-game-of-life"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
conlife = { path = "../conlife" }
open-oak = { path = "../open-oak" }
